### ISSUE TITLE
Need to combine to all images in single Folder 

### ISSUE THREAD

**Issue by bandya2003** [bandya2003/InternshipProject.github.io#2]
Add all Images to one folder

**Comment by Deevyn9** [comment]
hi, can you assign it to me?

**Comment by williamwebs** [comment]
Anyone on this project yet?
in none, I will like to help putting all the images in a single folder.

**Comment by bandya2003** [comment]
Sure I'll assign it you @Deevyn9

**Comment by Deevyn9** [comment]
Hi, @williamwebs  already worked on the issue

**Comment by Deevyn9** [comment]
I ended up adding target='blank' to the links
